# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/derek/dev/python/irec/telemetry/gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 653)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "background-color: lightgrey;\n"
                                 "}\n"
                                 "QCheckBox {\n"
                                 "color: white;\n"
                                 "font: 14pt \"Hack\";\n"
                                 "}\n"
                                 "QCheckBox::indicator {\n"
                                 "border: 1px solid white;\n"
                                 "}\n"
                                 "QCheckBox::indicator:checked {\n"
                                 "background-color: lime;\n"
                                 "}\n"
                                 "QCheckBox::indicator:unchecked {\n"
                                 "background-color: red;\n"
                                 "}\n"
                                 "QLabel {\n"
                                 "color: white;\n"
                                 "font: 14pt \"Hack\";\n"
                                 "background-color: grey;\n"
                                 "}\n"
                                 "Line {\n"
                                 "color: white;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vLayout_left_title = QtWidgets.QVBoxLayout()
        self.vLayout_left_title.setObjectName("vLayout_left_title")
        self.l_mainTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_mainTitle.sizePolicy().hasHeightForWidth())
        self.l_mainTitle.setSizePolicy(sizePolicy)
        self.l_mainTitle.setMinimumSize(QtCore.QSize(241, 23))
        self.l_mainTitle.setObjectName("l_mainTitle")
        self.vLayout_left_title.addWidget(self.l_mainTitle)
        self.hLayout_left = QtWidgets.QHBoxLayout()
        self.hLayout_left.setObjectName("hLayout_left")
        self.checkBox_telem = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_telem.setChecked(True)
        self.checkBox_telem.setObjectName("checkBox_telem")
        self.hLayout_left.addWidget(self.checkBox_telem)
        self.vLayout_stats = QtWidgets.QVBoxLayout()
        self.vLayout_stats.setObjectName("vLayout_stats")
        self.vLayout_avionics = QtWidgets.QVBoxLayout()
        self.vLayout_avionics.setObjectName("vLayout_avionics")
        self.l_avionics = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_avionics.sizePolicy().hasHeightForWidth())
        self.l_avionics.setSizePolicy(sizePolicy)
        self.l_avionics.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.l_avionics.setObjectName("l_avionics")
        self.vLayout_avionics.addWidget(self.l_avionics)
        self.hLayout_avionics_table = QtWidgets.QHBoxLayout()
        self.hLayout_avionics_table.setObjectName("hLayout_avionics_table")
        self.vLayout_avionics_titles = QtWidgets.QVBoxLayout()
        self.vLayout_avionics_titles.setObjectName("vLayout_avionics_titles")
        self.l_title_velocity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_title_velocity.sizePolicy().hasHeightForWidth())
        self.l_title_velocity.setSizePolicy(sizePolicy)
        self.l_title_velocity.setMinimumSize(QtCore.QSize(92, 23))
        self.l_title_velocity.setObjectName("l_title_velocity")
        self.vLayout_avionics_titles.addWidget(self.l_title_velocity)
        self.l_title_altitude = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.l_title_altitude.sizePolicy().hasHeightForWidth())
        self.l_title_altitude.setSizePolicy(sizePolicy)
        self.l_title_altitude.setMinimumSize(QtCore.QSize(92, 23))
        self.l_title_altitude.setObjectName("l_title_altitude")
        self.vLayout_avionics_titles.addWidget(self.l_title_altitude)
        self.hLayout_avionics_table.addLayout(self.vLayout_avionics_titles)
        self.vLayout_avionics_data = QtWidgets.QVBoxLayout()
        self.vLayout_avionics_data.setObjectName("vLayout_avionics_data")
        self.l_data_velocity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_data_velocity.sizePolicy().hasHeightForWidth())
        self.l_data_velocity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.l_data_velocity.setFont(font)
        self.l_data_velocity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_data_velocity.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_velocity.setObjectName("l_data_velocity")
        self.vLayout_avionics_data.addWidget(self.l_data_velocity)
        self.l_data_meter = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_data_meter.sizePolicy().hasHeightForWidth())
        self.l_data_meter.setSizePolicy(sizePolicy)
        self.l_data_meter.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_meter.setObjectName("l_data_meter")
        self.vLayout_avionics_data.addWidget(self.l_data_meter)
        self.l_data_feet = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_data_feet.sizePolicy().hasHeightForWidth())
        self.l_data_feet.setSizePolicy(sizePolicy)
        self.l_data_feet.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_feet.setObjectName("l_data_feet")
        self.vLayout_avionics_data.addWidget(self.l_data_feet)
        self.hLayout_avionics_table.addLayout(self.vLayout_avionics_data)
        self.vLayout_avionics_units = QtWidgets.QVBoxLayout()
        self.vLayout_avionics_units.setObjectName("vLayout_avionics_units")
        self.l_units_velocity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_units_velocity.sizePolicy().hasHeightForWidth())
        self.l_units_velocity.setSizePolicy(sizePolicy)
        self.l_units_velocity.setMinimumSize(QtCore.QSize(35, 23))
        self.l_units_velocity.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_velocity.setObjectName("l_units_velocity")
        self.vLayout_avionics_units.addWidget(self.l_units_velocity)
        self.l_units_meter = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_units_meter.sizePolicy().hasHeightForWidth())
        self.l_units_meter.setSizePolicy(sizePolicy)
        self.l_units_meter.setMinimumSize(QtCore.QSize(12, 23))
        self.l_units_meter.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_meter.setObjectName("l_units_meter")
        self.vLayout_avionics_units.addWidget(self.l_units_meter)
        self.l_units_feet = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_units_feet.sizePolicy().hasHeightForWidth())
        self.l_units_feet.setSizePolicy(sizePolicy)
        self.l_units_feet.setMinimumSize(QtCore.QSize(23, 23))
        self.l_units_feet.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_feet.setObjectName("l_units_feet")
        self.vLayout_avionics_units.addWidget(self.l_units_feet)
        self.hLayout_avionics_table.addLayout(self.vLayout_avionics_units)
        self.vLayout_avionics.addLayout(self.hLayout_avionics_table)
        self.vLayout_stats.addLayout(self.vLayout_avionics)
        self.vLayout_imu = QtWidgets.QVBoxLayout()
        self.vLayout_imu.setObjectName("vLayout_imu")
        self.l_imu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_imu.sizePolicy().hasHeightForWidth())
        self.l_imu.setSizePolicy(sizePolicy)
        self.l_imu.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.l_imu.setObjectName("l_imu")
        self.vLayout_imu.addWidget(self.l_imu)
        self.hLayout_imu_table = QtWidgets.QHBoxLayout()
        self.hLayout_imu_table.setObjectName("hLayout_imu_table")
        self.hLayout_accel_table = QtWidgets.QHBoxLayout()
        self.hLayout_accel_table.setObjectName("hLayout_accel_table")
        self.vLayout_accel_titles = QtWidgets.QVBoxLayout()
        self.vLayout_accel_titles.setObjectName("vLayout_accel_titles")
        self.l_title_Ax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Ax.sizePolicy().hasHeightForWidth())
        self.l_title_Ax.setSizePolicy(sizePolicy)
        self.l_title_Ax.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Ax.setObjectName("l_title_Ax")
        self.vLayout_accel_titles.addWidget(self.l_title_Ax)
        self.l_title_Ay = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Ay.sizePolicy().hasHeightForWidth())
        self.l_title_Ay.setSizePolicy(sizePolicy)
        self.l_title_Ay.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Ay.setObjectName("l_title_Ay")
        self.vLayout_accel_titles.addWidget(self.l_title_Ay)
        self.l_title_Az = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Az.sizePolicy().hasHeightForWidth())
        self.l_title_Az.setSizePolicy(sizePolicy)
        self.l_title_Az.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Az.setObjectName("l_title_Az")
        self.vLayout_accel_titles.addWidget(self.l_title_Az)
        self.hLayout_accel_table.addLayout(self.vLayout_accel_titles)
        self.vLayout_accel_data = QtWidgets.QVBoxLayout()
        self.vLayout_accel_data.setObjectName("vLayout_accel_data")
        self.l_data_Ax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Ax.sizePolicy().hasHeightForWidth())
        self.l_data_Ax.setSizePolicy(sizePolicy)
        self.l_data_Ax.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Ax.setObjectName("l_data_Ax")
        self.vLayout_accel_data.addWidget(self.l_data_Ax)
        self.l_data_Ay = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Ay.sizePolicy().hasHeightForWidth())
        self.l_data_Ay.setSizePolicy(sizePolicy)
        self.l_data_Ay.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Ay.setObjectName("l_data_Ay")
        self.vLayout_accel_data.addWidget(self.l_data_Ay)
        self.l_data_Az = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Az.sizePolicy().hasHeightForWidth())
        self.l_data_Az.setSizePolicy(sizePolicy)
        self.l_data_Az.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Az.setObjectName("l_data_Az")
        self.vLayout_accel_data.addWidget(self.l_data_Az)
        self.hLayout_accel_table.addLayout(self.vLayout_accel_data)
        self.vLayout_accel_units = QtWidgets.QVBoxLayout()
        self.vLayout_accel_units.setObjectName("vLayout_accel_units")
        self.l_units_Ax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Ax.sizePolicy().hasHeightForWidth())
        self.l_units_Ax.setSizePolicy(sizePolicy)
        self.l_units_Ax.setMinimumSize(QtCore.QSize(42, 23))
        self.l_units_Ax.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Ax.setObjectName("l_units_Ax")
        self.vLayout_accel_units.addWidget(self.l_units_Ax)
        self.l_units_Ay = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Ay.sizePolicy().hasHeightForWidth())
        self.l_units_Ay.setSizePolicy(sizePolicy)
        self.l_units_Ay.setMinimumSize(QtCore.QSize(42, 23))
        self.l_units_Ay.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Ay.setObjectName("l_units_Ay")
        self.vLayout_accel_units.addWidget(self.l_units_Ay)
        self.l_units_Az = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Az.sizePolicy().hasHeightForWidth())
        self.l_units_Az.setSizePolicy(sizePolicy)
        self.l_units_Az.setMinimumSize(QtCore.QSize(42, 23))
        self.l_units_Az.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Az.setObjectName("l_units_Az")
        self.vLayout_accel_units.addWidget(self.l_units_Az)
        self.hLayout_accel_table.addLayout(self.vLayout_accel_units)
        self.hLayout_imu_table.addLayout(self.hLayout_accel_table)
        self.imu_separator = QtWidgets.QFrame(self.centralwidget)
        self.imu_separator.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imu_separator.setLineWidth(5)
        self.imu_separator.setFrameShape(QtWidgets.QFrame.VLine)
        self.imu_separator.setObjectName("imu_separator")
        self.hLayout_imu_table.addWidget(self.imu_separator)
        self.hLayout_gyro_table = QtWidgets.QHBoxLayout()
        self.hLayout_gyro_table.setObjectName("hLayout_gyro_table")
        self.vLayout_gyro_titles = QtWidgets.QVBoxLayout()
        self.vLayout_gyro_titles.setObjectName("vLayout_gyro_titles")
        self.l_title_Gx = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Gx.sizePolicy().hasHeightForWidth())
        self.l_title_Gx.setSizePolicy(sizePolicy)
        self.l_title_Gx.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Gx.setObjectName("l_title_Gx")
        self.vLayout_gyro_titles.addWidget(self.l_title_Gx)
        self.l_title_Gy = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Gy.sizePolicy().hasHeightForWidth())
        self.l_title_Gy.setSizePolicy(sizePolicy)
        self.l_title_Gy.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Gy.setObjectName("l_title_Gy")
        self.vLayout_gyro_titles.addWidget(self.l_title_Gy)
        self.l_title_Gz = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_Gz.sizePolicy().hasHeightForWidth())
        self.l_title_Gz.setSizePolicy(sizePolicy)
        self.l_title_Gz.setMinimumSize(QtCore.QSize(23, 23))
        self.l_title_Gz.setObjectName("l_title_Gz")
        self.vLayout_gyro_titles.addWidget(self.l_title_Gz)
        self.hLayout_gyro_table.addLayout(self.vLayout_gyro_titles)
        self.vLayout_gyro_data = QtWidgets.QVBoxLayout()
        self.vLayout_gyro_data.setObjectName("vLayout_gyro_data")
        self.l_data_Gx = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Gx.sizePolicy().hasHeightForWidth())
        self.l_data_Gx.setSizePolicy(sizePolicy)
        self.l_data_Gx.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Gx.setObjectName("l_data_Gx")
        self.vLayout_gyro_data.addWidget(self.l_data_Gx)
        self.l_data_Gy = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Gy.sizePolicy().hasHeightForWidth())
        self.l_data_Gy.setSizePolicy(sizePolicy)
        self.l_data_Gy.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Gy.setObjectName("l_data_Gy")
        self.vLayout_gyro_data.addWidget(self.l_data_Gy)
        self.l_data_Gz = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_Gz.sizePolicy().hasHeightForWidth())
        self.l_data_Gz.setSizePolicy(sizePolicy)
        self.l_data_Gz.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_Gz.setObjectName("l_data_Gz")
        self.vLayout_gyro_data.addWidget(self.l_data_Gz)
        self.hLayout_gyro_table.addLayout(self.vLayout_gyro_data)
        self.vLayout_gyro_units = QtWidgets.QVBoxLayout()
        self.vLayout_gyro_units.setObjectName("vLayout_gyro_units")
        self.l_units_Gx = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Gx.sizePolicy().hasHeightForWidth())
        self.l_units_Gx.setSizePolicy(sizePolicy)
        self.l_units_Gx.setMinimumSize(QtCore.QSize(35, 23))
        self.l_units_Gx.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Gx.setObjectName("l_units_Gx")
        self.vLayout_gyro_units.addWidget(self.l_units_Gx)
        self.l_units_Gy = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Gy.sizePolicy().hasHeightForWidth())
        self.l_units_Gy.setSizePolicy(sizePolicy)
        self.l_units_Gy.setMinimumSize(QtCore.QSize(35, 23))
        self.l_units_Gy.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Gy.setObjectName("l_units_Gy")
        self.vLayout_gyro_units.addWidget(self.l_units_Gy)
        self.l_units_Gz = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_Gz.sizePolicy().hasHeightForWidth())
        self.l_units_Gz.setSizePolicy(sizePolicy)
        self.l_units_Gz.setMinimumSize(QtCore.QSize(35, 23))
        self.l_units_Gz.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_Gz.setObjectName("l_units_Gz")
        self.vLayout_gyro_units.addWidget(self.l_units_Gz)
        self.hLayout_gyro_table.addLayout(self.vLayout_gyro_units)
        self.hLayout_imu_table.addLayout(self.hLayout_gyro_table)
        self.vLayout_imu.addLayout(self.hLayout_imu_table)
        self.vLayout_stats.addLayout(self.vLayout_imu)
        self.vLayout_status = QtWidgets.QVBoxLayout()
        self.vLayout_status.setObjectName("vLayout_status")
        self.l_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_status.sizePolicy().hasHeightForWidth())
        self.l_status.setSizePolicy(sizePolicy)
        self.l_status.setAutoFillBackground(False)
        self.l_status.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.l_status.setObjectName("l_status")
        self.vLayout_status.addWidget(self.l_status)
        self.hLayout_status_table = QtWidgets.QHBoxLayout()
        self.hLayout_status_table.setObjectName("hLayout_status_table")
        self.vLayout_status_titles = QtWidgets.QVBoxLayout()
        self.vLayout_status_titles.setObjectName("vLayout_status_titles")
        self.l_title_voltage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_voltage.sizePolicy().hasHeightForWidth())
        self.l_title_voltage.setSizePolicy(sizePolicy)
        self.l_title_voltage.setMinimumSize(QtCore.QSize(81, 23))
        self.l_title_voltage.setObjectName("l_title_voltage")
        self.vLayout_status_titles.addWidget(self.l_title_voltage)
        self.l_title_temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_title_temperature.sizePolicy().hasHeightForWidth())
        self.l_title_temperature.setSizePolicy(sizePolicy)
        self.l_title_temperature.setMinimumSize(QtCore.QSize(126, 23))
        self.l_title_temperature.setObjectName("l_title_temperature")
        self.vLayout_status_titles.addWidget(self.l_title_temperature)
        self.l_title_atmPressure = QtWidgets.QLabel(self.centralwidget)
        self.l_title_atmPressure.setObjectName("l_title_atmPressure")
        self.vLayout_status_titles.addWidget(self.l_title_atmPressure)
        self.hLayout_status_table.addLayout(self.vLayout_status_titles)
        self.vLayout_status_data = QtWidgets.QVBoxLayout()
        self.vLayout_status_data.setObjectName("vLayout_status_data")
        self.l_data_voltage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_voltage.sizePolicy().hasHeightForWidth())
        self.l_data_voltage.setSizePolicy(sizePolicy)
        self.l_data_voltage.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_voltage.setObjectName("l_data_voltage")
        self.vLayout_status_data.addWidget(self.l_data_voltage)
        self.l_data_temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_temperature.sizePolicy().hasHeightForWidth())
        self.l_data_temperature.setSizePolicy(sizePolicy)
        self.l_data_temperature.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_temperature.setObjectName("l_data_temperature")
        self.vLayout_status_data.addWidget(self.l_data_temperature)
        self.l_data_atmPressure = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_data_atmPressure.sizePolicy().hasHeightForWidth())
        self.l_data_atmPressure.setSizePolicy(sizePolicy)
        self.l_data_atmPressure.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_data_atmPressure.setObjectName("l_data_atmPressure")
        self.vLayout_status_data.addWidget(self.l_data_atmPressure)
        self.hLayout_status_table.addLayout(self.vLayout_status_data)
        self.vLayout_status_units = QtWidgets.QVBoxLayout()
        self.vLayout_status_units.setObjectName("vLayout_status_units")
        self.l_units__voltage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units__voltage.sizePolicy().hasHeightForWidth())
        self.l_units__voltage.setSizePolicy(sizePolicy)
        self.l_units__voltage.setMinimumSize(QtCore.QSize(12, 23))
        self.l_units__voltage.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units__voltage.setObjectName("l_units__voltage")
        self.vLayout_status_units.addWidget(self.l_units__voltage)
        self.l_units_temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_temperature.sizePolicy().hasHeightForWidth())
        self.l_units_temperature.setSizePolicy(sizePolicy)
        self.l_units_temperature.setMinimumSize(QtCore.QSize(23, 23))
        self.l_units_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_temperature.setObjectName("l_units_temperature")
        self.vLayout_status_units.addWidget(self.l_units_temperature)
        self.l_units_atmPressure = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_units_atmPressure.sizePolicy().hasHeightForWidth())
        self.l_units_atmPressure.setSizePolicy(sizePolicy)
        self.l_units_atmPressure.setMinimumSize(QtCore.QSize(35, 23))
        self.l_units_atmPressure.setAlignment(QtCore.Qt.AlignCenter)
        self.l_units_atmPressure.setObjectName("l_units_atmPressure")
        self.vLayout_status_units.addWidget(self.l_units_atmPressure)
        self.hLayout_status_table.addLayout(self.vLayout_status_units)
        self.vLayout_status.addLayout(self.hLayout_status_table)
        self.vLayout_stats.addLayout(self.vLayout_status)
        self.hLayout_left.addLayout(self.vLayout_stats)
        self.vLayout_left_title.addLayout(self.hLayout_left)
        self.horizontalLayout.addLayout(self.vLayout_left_title)
        self.vLayout_right_graphs = QtWidgets.QVBoxLayout()
        self.vLayout_right_graphs.setObjectName("vLayout_right_graphs")
        self.mpl_graphs = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_graphs.sizePolicy().hasHeightForWidth())
        self.mpl_graphs.setSizePolicy(sizePolicy)
        self.mpl_graphs.setObjectName("mpl_graphs")
        self.vLayout_right_graphs.addWidget(self.mpl_graphs)
        self.horizontalLayout.addLayout(self.vLayout_right_graphs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEDS-UCF IREC Telemetry"))
        self.l_mainTitle.setText(_translate("MainWindow", "<b>ROCKET LAUNCH CONTROL</b>"))
        self.checkBox_telem.setText(_translate("MainWindow", "Telemetry Activated?"))
        self.l_avionics.setText(_translate("MainWindow", "<b>AVIONICS</b>"))
        self.l_title_velocity.setText(_translate("MainWindow", "Velocity"))
        self.l_title_altitude.setText(_translate("MainWindow", "Altitude"))
        self.l_data_velocity.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_meter.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_feet.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_units_velocity.setText(_translate("MainWindow", "m/s"))
        self.l_units_meter.setText(_translate("MainWindow", "m"))
        self.l_units_feet.setText(_translate("MainWindow", "ft"))
        self.l_imu.setText(_translate("MainWindow", "<b>IMU</b>"))
        self.l_title_Ax.setText(_translate("MainWindow", "Ax"))
        self.l_title_Ay.setText(_translate("MainWindow", "Ay"))
        self.l_title_Az.setText(_translate("MainWindow", "Az"))
        self.l_data_Ax.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_Ay.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_Az.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_units_Ax.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.l_units_Ay.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.l_units_Az.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.l_title_Gx.setText(_translate("MainWindow", "Gx"))
        self.l_title_Gy.setText(_translate("MainWindow", "Gy"))
        self.l_title_Gz.setText(_translate("MainWindow", "Gz"))
        self.l_data_Gx.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_Gy.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_Gz.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_units_Gx.setText(_translate("MainWindow", "°/s"))
        self.l_units_Gy.setText(_translate("MainWindow", "°/s"))
        self.l_units_Gz.setText(_translate("MainWindow", "°/s"))
        self.l_status.setText(_translate("MainWindow", "<b>STATUS</b>"))
        self.l_title_voltage.setText(_translate("MainWindow", "Voltage"))
        self.l_title_temperature.setText(_translate("MainWindow", "Temperature"))
        self.l_title_atmPressure.setText(_translate("MainWindow", "Atm. Pressure"))
        self.l_data_voltage.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_temperature.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_data_atmPressure.setText(_translate("MainWindow", "-999999999.999999"))
        self.l_units__voltage.setText(_translate("MainWindow", "V"))
        self.l_units_temperature.setText(_translate("MainWindow", "°C"))
        self.l_units_atmPressure.setText(_translate("MainWindow", "bar"))


from mplwidget import MplWidget
